"""empty message

Revision ID: 489716150590
Revises: 
Create Date: 2024-01-04 18:10:23.283359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489716150590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('library',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('isbn', sa.String(length=150), nullable=False),
    sa.Column('book_title', sa.String(length=50), nullable=False),
    sa.Column('author_name', sa.String(length=50), nullable=True),
    sa.Column('book_length', sa.String(length=50), nullable=True),
    sa.Column('publisher', sa.String(length=50), nullable=True),
    sa.Column('book_format', sa.String(length=10), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library')
    op.drop_table('user')
    # ### end Alembic commands ###
